BEGIN TRANSACTION;
INSERT INTO "country" VALUES(194,'Abkhazia');
INSERT INTO "country" VALUES(1,'Afghanistan');
INSERT INTO "country" VALUES(258,'Aland');
INSERT INTO "country" VALUES(2,'Albania');
INSERT INTO "country" VALUES(3,'Algeria');
INSERT INTO "country" VALUES(238,'American Samoa');
INSERT INTO "country" VALUES(4,'Andorra');
INSERT INTO "country" VALUES(5,'Angola');
INSERT INTO "country" VALUES(223,'Anguilla');
INSERT INTO "country" VALUES(6,'Antigua and Barbuda');
INSERT INTO "country" VALUES(7,'Argentina');
INSERT INTO "country" VALUES(8,'Armenia');
INSERT INTO "country" VALUES(259,'Aruba');
INSERT INTO "country" VALUES(262,'Ascension');
INSERT INTO "country" VALUES(201,'Ashmore and Cartier Islands');
INSERT INTO "country" VALUES(9,'Australia');
INSERT INTO "country" VALUES(268,'Australian Antarctic Territory');
INSERT INTO "country" VALUES(10,'Austria');
INSERT INTO "country" VALUES(11,'Azerbaijan');
INSERT INTO "country" VALUES(12,'Bahamas');
INSERT INTO "country" VALUES(13,'Bahrain');
INSERT INTO "country" VALUES(239,'Baker Island');
INSERT INTO "country" VALUES(14,'Bangladesh');
INSERT INTO "country" VALUES(15,'Barbados');
INSERT INTO "country" VALUES(16,'Belarus');
INSERT INTO "country" VALUES(17,'Belgium');
INSERT INTO "country" VALUES(18,'Belize');
INSERT INTO "country" VALUES(19,'Benin');
INSERT INTO "country" VALUES(224,'Bermuda');
INSERT INTO "country" VALUES(20,'Bhutan');
INSERT INTO "country" VALUES(21,'Bolivia');
INSERT INTO "country" VALUES(22,'Bosnia and Herzegovina');
INSERT INTO "country" VALUES(23,'Botswana');
INSERT INTO "country" VALUES(216,'Bouvet Island');
INSERT INTO "country" VALUES(24,'Brazil');
INSERT INTO "country" VALUES(272,'British Antarctic Territory');
INSERT INTO "country" VALUES(225,'British Indian Ocean Territory');
INSERT INTO "country" VALUES(226,'British Sovereign Base Areas');
INSERT INTO "country" VALUES(227,'British Virgin Islands');
INSERT INTO "country" VALUES(25,'Brunei');
INSERT INTO "country" VALUES(26,'Bulgaria');
INSERT INTO "country" VALUES(27,'Burkina Faso');
INSERT INTO "country" VALUES(28,'Burundi');
INSERT INTO "country" VALUES(29,'Cambodia');
INSERT INTO "country" VALUES(30,'Cameroon');
INSERT INTO "country" VALUES(31,'Canada');
INSERT INTO "country" VALUES(32,'Cape Verde');
INSERT INTO "country" VALUES(228,'Cayman Islands');
INSERT INTO "country" VALUES(33,'Central African Republic');
INSERT INTO "country" VALUES(34,'Chad');
INSERT INTO "country" VALUES(35,'Chile');
INSERT INTO "country" VALUES(36,'China');
INSERT INTO "country" VALUES(202,'Christmas Island');
INSERT INTO "country" VALUES(215,'Clipperton Island');
INSERT INTO "country" VALUES(203,'Cocos (Keeling) Islands');
INSERT INTO "country" VALUES(37,'Colombia');
INSERT INTO "country" VALUES(38,'Comoros');
INSERT INTO "country" VALUES(39,'Congo');
INSERT INTO "country" VALUES(217,'Cook Islands');
INSERT INTO "country" VALUES(204,'Coral Sea Islands');
INSERT INTO "country" VALUES(41,'Costa Rica');
INSERT INTO "country" VALUES(42,'Cote d''Ivoire (Ivory Coast)');
INSERT INTO "country" VALUES(43,'Croatia');
INSERT INTO "country" VALUES(44,'Cuba');
INSERT INTO "country" VALUES(45,'Cyprus');
INSERT INTO "country" VALUES(46,'Czech Republic');
INSERT INTO "country" VALUES(40,'Democratic Republic of Congo');
INSERT INTO "country" VALUES(47,'Denmark');
INSERT INTO "country" VALUES(48,'Djibouti');
INSERT INTO "country" VALUES(49,'Dominica');
INSERT INTO "country" VALUES(50,'Dominican Republic');
INSERT INTO "country" VALUES(51,'Ecuador');
INSERT INTO "country" VALUES(52,'Egypt');
INSERT INTO "country" VALUES(53,'El Salvador');
INSERT INTO "country" VALUES(54,'Equatorial Guinea');
INSERT INTO "country" VALUES(55,'Eritrea');
INSERT INTO "country" VALUES(56,'Estonia');
INSERT INTO "country" VALUES(57,'Ethiopia');
INSERT INTO "country" VALUES(229,'Falkland Islands (Islas Malvinas)');
INSERT INTO "country" VALUES(252,'Faroe Islands');
INSERT INTO "country" VALUES(58,'Fiji');
INSERT INTO "country" VALUES(59,'Finland');
INSERT INTO "country" VALUES(60,'France');
INSERT INTO "country" VALUES(254,'French Guiana');
INSERT INTO "country" VALUES(208,'French Polynesia');
INSERT INTO "country" VALUES(214,'French Southern and Antarctic Lands');
INSERT INTO "country" VALUES(61,'Gabon');
INSERT INTO "country" VALUES(62,'Gambia');
INSERT INTO "country" VALUES(63,'Georgia');
INSERT INTO "country" VALUES(64,'Germany');
INSERT INTO "country" VALUES(65,'Ghana');
INSERT INTO "country" VALUES(230,'Gibraltar');
INSERT INTO "country" VALUES(66,'Greece');
INSERT INTO "country" VALUES(253,'Greenland');
INSERT INTO "country" VALUES(67,'Grenada');
INSERT INTO "country" VALUES(255,'Guadeloupe');
INSERT INTO "country" VALUES(240,'Guam');
INSERT INTO "country" VALUES(68,'Guatemala');
INSERT INTO "country" VALUES(220,'Guernsey');
INSERT INTO "country" VALUES(69,'Guinea');
INSERT INTO "country" VALUES(70,'Guinea-Bissau');
INSERT INTO "country" VALUES(71,'Guyana');
INSERT INTO "country" VALUES(72,'Haiti');
INSERT INTO "country" VALUES(205,'Heard Island and McDonald Islands');
INSERT INTO "country" VALUES(73,'Honduras');
INSERT INTO "country" VALUES(250,'Hong Kong');
INSERT INTO "country" VALUES(241,'Howland Island');
INSERT INTO "country" VALUES(74,'Hungary');
INSERT INTO "country" VALUES(75,'Iceland');
INSERT INTO "country" VALUES(76,'India');
INSERT INTO "country" VALUES(77,'Indonesia');
INSERT INTO "country" VALUES(78,'Iran');
INSERT INTO "country" VALUES(79,'Iraq');
INSERT INTO "country" VALUES(80,'Ireland');
INSERT INTO "country" VALUES(221,'Isle of Man');
INSERT INTO "country" VALUES(81,'Israel');
INSERT INTO "country" VALUES(82,'Italy');
INSERT INTO "country" VALUES(83,'Jamaica');
INSERT INTO "country" VALUES(84,'Japan');
INSERT INTO "country" VALUES(242,'Jarvis Island');
INSERT INTO "country" VALUES(222,'Jersey');
INSERT INTO "country" VALUES(243,'Johnston Atoll');
INSERT INTO "country" VALUES(85,'Jordan');
INSERT INTO "country" VALUES(86,'Kazakhstan');
INSERT INTO "country" VALUES(87,'Kenya');
INSERT INTO "country" VALUES(244,'Kingman Reef');
INSERT INTO "country" VALUES(88,'Kiribati');
INSERT INTO "country" VALUES(91,'Kuwait');
INSERT INTO "country" VALUES(92,'Kyrgyzstan');
INSERT INTO "country" VALUES(93,'Laos');
INSERT INTO "country" VALUES(94,'Latvia');
INSERT INTO "country" VALUES(95,'Lebanon');
INSERT INTO "country" VALUES(96,'Lesotho');
INSERT INTO "country" VALUES(97,'Liberia');
INSERT INTO "country" VALUES(98,'Libya');
INSERT INTO "country" VALUES(99,'Liechtenstein');
INSERT INTO "country" VALUES(100,'Lithuania');
INSERT INTO "country" VALUES(101,'Luxembourg');
INSERT INTO "country" VALUES(251,'Macau');
INSERT INTO "country" VALUES(102,'Macedonia');
INSERT INTO "country" VALUES(103,'Madagascar');
INSERT INTO "country" VALUES(104,'Malawi');
INSERT INTO "country" VALUES(105,'Malaysia');
INSERT INTO "country" VALUES(106,'Maldives');
INSERT INTO "country" VALUES(107,'Mali');
INSERT INTO "country" VALUES(108,'Malta');
INSERT INTO "country" VALUES(109,'Marshall Islands');
INSERT INTO "country" VALUES(256,'Martinique');
INSERT INTO "country" VALUES(110,'Mauritania');
INSERT INTO "country" VALUES(111,'Mauritius');
INSERT INTO "country" VALUES(209,'Mayotte');
INSERT INTO "country" VALUES(112,'Mexico');
INSERT INTO "country" VALUES(113,'Micronesia');
INSERT INTO "country" VALUES(245,'Midway Islands');
INSERT INTO "country" VALUES(114,'Moldova');
INSERT INTO "country" VALUES(115,'Monaco');
INSERT INTO "country" VALUES(116,'Mongolia');
INSERT INTO "country" VALUES(117,'Montenegro');
INSERT INTO "country" VALUES(231,'Montserrat');
INSERT INTO "country" VALUES(118,'Morocco');
INSERT INTO "country" VALUES(119,'Mozambique');
INSERT INTO "country" VALUES(120,'Myanmar (Burma)');
INSERT INTO "country" VALUES(196,'Nagorno-Karabakh');
INSERT INTO "country" VALUES(121,'Namibia');
INSERT INTO "country" VALUES(122,'Nauru');
INSERT INTO "country" VALUES(246,'Navassa Island');
INSERT INTO "country" VALUES(123,'Nepal');
INSERT INTO "country" VALUES(124,'Netherlands');
INSERT INTO "country" VALUES(260,'Netherlands Antilles');
INSERT INTO "country" VALUES(207,'New Caledonia');
INSERT INTO "country" VALUES(125,'New Zealand');
INSERT INTO "country" VALUES(126,'Nicaragua');
INSERT INTO "country" VALUES(127,'Niger');
INSERT INTO "country" VALUES(128,'Nigeria');
INSERT INTO "country" VALUES(218,'Niue');
INSERT INTO "country" VALUES(206,'Norfolk Island');
INSERT INTO "country" VALUES(89,'North Korea');
INSERT INTO "country" VALUES(197,'Northern Cyprus');
INSERT INTO "country" VALUES(236,'Northern Mariana Islands');
INSERT INTO "country" VALUES(129,'Norway');
INSERT INTO "country" VALUES(130,'Oman');
INSERT INTO "country" VALUES(131,'Pakistan');
INSERT INTO "country" VALUES(132,'Palau');
INSERT INTO "country" VALUES(247,'Palmyra Atoll');
INSERT INTO "country" VALUES(133,'Panama');
INSERT INTO "country" VALUES(134,'Papua New Guinea');
INSERT INTO "country" VALUES(135,'Paraguay');
INSERT INTO "country" VALUES(136,'Peru');
INSERT INTO "country" VALUES(270,'Peter I Island');
INSERT INTO "country" VALUES(137,'Philippines');
INSERT INTO "country" VALUES(232,'Pitcairn Islands');
INSERT INTO "country" VALUES(138,'Poland');
INSERT INTO "country" VALUES(139,'Portugal');
INSERT INTO "country" VALUES(198,'Pridnestrovie (Transnistria)');
INSERT INTO "country" VALUES(237,'Puerto Rico');
INSERT INTO "country" VALUES(140,'Qatar');
INSERT INTO "country" VALUES(271,'Queen Maud Land');
INSERT INTO "country" VALUES(257,'Reunion');
INSERT INTO "country" VALUES(141,'Romania');
INSERT INTO "country" VALUES(269,'Ross Dependency');
INSERT INTO "country" VALUES(142,'Russia');
INSERT INTO "country" VALUES(143,'Rwanda');
INSERT INTO "country" VALUES(210,'Saint Barthelemy');
INSERT INTO "country" VALUES(233,'Saint Helena');
INSERT INTO "country" VALUES(144,'Saint Kitts and Nevis');
INSERT INTO "country" VALUES(145,'Saint Lucia');
INSERT INTO "country" VALUES(211,'Saint Martin');
INSERT INTO "country" VALUES(212,'Saint Pierre and Miquelon');
INSERT INTO "country" VALUES(146,'Saint Vincent and the Grenadines');
INSERT INTO "country" VALUES(147,'Samoa');
INSERT INTO "country" VALUES(148,'San Marino');
INSERT INTO "country" VALUES(149,'Sao Tome and Principe');
INSERT INTO "country" VALUES(150,'Saudi Arabia');
INSERT INTO "country" VALUES(151,'Senegal');
INSERT INTO "country" VALUES(152,'Serbia');
INSERT INTO "country" VALUES(153,'Seychelles');
INSERT INTO "country" VALUES(154,'Sierra Leone');
INSERT INTO "country" VALUES(155,'Singapore');
INSERT INTO "country" VALUES(156,'Slovakia');
INSERT INTO "country" VALUES(157,'Slovenia');
INSERT INTO "country" VALUES(158,'Solomon Islands');
INSERT INTO "country" VALUES(159,'Somalia');
INSERT INTO "country" VALUES(199,'Somaliland');
INSERT INTO "country" VALUES(160,'South Africa');
INSERT INTO "country" VALUES(234,'South Georgia & South Sandwich Islands');
INSERT INTO "country" VALUES(90,'South Korea');
INSERT INTO "country" VALUES(200,'South Ossetia');
INSERT INTO "country" VALUES(161,'Spain');
INSERT INTO "country" VALUES(162,'Sri Lanka');
INSERT INTO "country" VALUES(163,'Sudan');
INSERT INTO "country" VALUES(164,'Suriname');
INSERT INTO "country" VALUES(261,'Svalbard');
INSERT INTO "country" VALUES(165,'Swaziland');
INSERT INTO "country" VALUES(166,'Sweden');
INSERT INTO "country" VALUES(167,'Switzerland');
INSERT INTO "country" VALUES(168,'Syria');
INSERT INTO "country" VALUES(195,'Taiwan');
INSERT INTO "country" VALUES(169,'Tajikistan');
INSERT INTO "country" VALUES(170,'Tanzania');
INSERT INTO "country" VALUES(171,'Thailand');
INSERT INTO "country" VALUES(172,'Timor-Leste (East Timor)');
INSERT INTO "country" VALUES(173,'Togo');
INSERT INTO "country" VALUES(219,'Tokelau');
INSERT INTO "country" VALUES(174,'Tonga');
INSERT INTO "country" VALUES(175,'Trinidad and Tobago');
INSERT INTO "country" VALUES(263,'Tristan da Cunha');
INSERT INTO "country" VALUES(176,'Tunisia');
INSERT INTO "country" VALUES(177,'Turkey');
INSERT INTO "country" VALUES(178,'Turkmenistan');
INSERT INTO "country" VALUES(235,'Turks and Caicos Islands');
INSERT INTO "country" VALUES(179,'Tuvalu');
INSERT INTO "country" VALUES(248,'U.S. Virgin Islands');
INSERT INTO "country" VALUES(180,'Uganda');
INSERT INTO "country" VALUES(181,'Ukraine');
INSERT INTO "country" VALUES(182,'United Arab Emirates');
INSERT INTO "country" VALUES(183,'United Kingdom');
INSERT INTO "country" VALUES(184,'United States');
INSERT INTO "country" VALUES(185,'Uruguay');
INSERT INTO "country" VALUES(186,'Uzbekistan');
INSERT INTO "country" VALUES(187,'Vanuatu');
INSERT INTO "country" VALUES(188,'Vatican City');
INSERT INTO "country" VALUES(189,'Venezuela');
INSERT INTO "country" VALUES(190,'Vietnam');
INSERT INTO "country" VALUES(249,'Wake Island');
INSERT INTO "country" VALUES(213,'Wallis and Futuna');
INSERT INTO "country" VALUES(191,'Yemen');
INSERT INTO "country" VALUES(192,'Zambia');
INSERT INTO "country" VALUES(193,'Zimbabwe');
INSERT INTO "skill" VALUES(12,'apache');
INSERT INTO "skill" VALUES(6,'c');
INSERT INTO "skill" VALUES(7,'c++');
INSERT INTO "skill" VALUES(10,'css');
INSERT INTO "skill" VALUES(15,'eclipse');
INSERT INTO "skill" VALUES(13,'emacs');
INSERT INTO "skill" VALUES(9,'html');
INSERT INTO "skill" VALUES(4,'java');
INSERT INTO "skill" VALUES(11,'javascript');
INSERT INTO "skill" VALUES(2,'mod_perl');
INSERT INTO "skill" VALUES(1,'perl');
INSERT INTO "skill" VALUES(5,'php');
INSERT INTO "skill" VALUES(8,'sql');
INSERT INTO "skill" VALUES(3,'unix');
INSERT INTO "skill" VALUES(14,'vi');
COMMIT;
